export const GET_FACULTIES_REQUEST = 'GET_FACULTIES_REQUEST'
export const GET_FACULTIES_SUCCESS = 'GET_FACULTIES_SUCCESS'
export const GET_FACULTIES_FAILED = 'GET_FACULTIES_FAILED'

export const GET_TIMETABLES_REQUEST = 'GET_TIMETABLES_REQUEST'
export const GET_TIMETABLES_SUCCESS = 'GET_TIMETABLES_SUCCESS'
export const GET_TIMETABLES_FAILED = 'GET_TIMETABLES_FAILED'

export const GET_TIMETABLE_REQUEST = 'GET_TIMETABLE_REQUEST'
export const GET_TIMETABLE_SUCCESS = 'GET_TIMETABLE_SUCCESS'
export const GET_TIMETABLE_FAILED = 'GET_TIMETABLE_FAILED'

export const SET_FIELD = 'SET_FIELD'

// Тестовая инициилизация
export const INIT_TIMETABLE_REQUEST = 'INIT_TIMETABLE_REQUEST'
export const INIT_TIMETABLE_SUCCESS = 'INIT_TIMETABLE_SUCCESS'
export const INIT_TIMETABLE_FAILED = 'INIT_TIMETABLE_FAILED'

// 1) Получение факультетов
export const INIT_FACULTIES_LIST_SUCCESS = 'INIT_FACULTIES_LIST_SUCCESS'
export const INIT_FACULTIES_LIST_FAILED = 'INIT_FACULTIES_LIST_FAILED'

// 2) Получение семестров факультета
export const INIT_SEMESTERS_LIST_REQUEST = 'INIT_SEMESTERS_LIST_REQUEST'
export const INIT_SEMESTERS_LIST_SUCCESS = 'INIT_SEMESTERS_LIST_SUCCESS'
export const INIT_SEMESTERS_LIST_FAILED = 'INIT_SEMESTERS_LIST_FAILED'

// 3) Выбор Бакалавриат/Магистратура
export const INIT_LEVEL = 'INIT_LEVEL'

// 4) Получение списка курсов и расписания
export const INIT_SOME_TIMETABLE_SUCCESS = 'INIT_SOME_TIMETABLE_SUCCESS'
export const INIT_SOME_TIMETABLE_FAILED = 'INIT_SOME_TIMETABLE_FAILED'

// Сброс расписания
export const CLEAR_TIMETABLE = 'CLEAR_TIMETABLE'