export const FIRST_LOAD_PAGE = 'FIRST_LOAD_PAGE'
export const FIRST_LOAD_PAGE_SUCCESS = 'FIRST_LOAD_PAGE_SUCCESS'
export const FIRST_LOAD_PAGE_FAILED = 'FIRST_LOAD_PAGE_FAILED'

// Изменение полей формы
export const CHANGE_FIELD_VALUE = 'CHANGE_FIELD_VALUE'
export const FACULTY_CHANGED = 'FACULTY_CHANGED'
export const SEMESTER_CHANGED = 'SEMESTER_CHANGED'
export const LEVEL_CHANGED = 'LEVEL_CHANGED'
export const COURCE_CHANGED = 'COURCE_CHANGED'
export const CHANGINT_FAILED = 'CHANGINT_FAILED'

// Подгрузка необходимых данных с сервера
export const LOAD_FACULTIES_REQUEST = 'LOAD_FACULTIES_REQUEST'
export const LOAD_FACULTIES_SUCCESS = 'LOAD_FACULTIES_SUCCESS'
export const LOAD_FACULTIES_FAILED  = 'LOAD_FACULTIES_FAILED'
