export const GET_FACULTIES_REQUEST = 'GET_FACULTIES_REQUEST'
export const GET_FACULTIES_SUCCESS = 'GET_FACULTIES_SUCCESS'
export const GET_FACULTIES_FAILED = 'GET_FACULTIES_FAILED'

export const GET_TIMETABLES_REQUEST = 'GET_TIMETABLES_REQUEST'
export const GET_TIMETABLES_SUCCESS = 'GET_TIMETABLES_SUCCESS'
export const GET_TIMETABLES_FAILED = 'GET_TIMETABLES_FAILED'